import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import theme from '@/theme';
import { ThemeProvider } from '@mui/material/styles';
import Navbar from './_components/Navbar/page';
import Footer from './_components/Footer/page';
import QueryWraped from './_components/QueryWraped/page';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <title>YallaNShop</title>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
              <QueryWraped>
                <Navbar />
                <main className='flex-grow'>{children}</main>
                <Footer />
              </QueryWraped>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
